export const ANG100 = {"code": "ANG100", "title": "Anglais général pour débutants", "ects": 6}
export const ANG320 = {"code": "ANG320", "title": "Anglais professionnel", "ects": 6}
export const ANG330 = {"code": "ANG330", "title": "Anglais professionnel", "ects": 6}
export const BCA001 = {"code": "BCA001", "title": "Initiation biologie-biochimie structurale", "ects": 6}
export const BNF104 = {"code": "BNF104", "title": "Utilisation et applications de la bio-informatique", "ects": 6}
export const CFA109 = {"code": "CFA109", "title": "Information comptable et management", "ects": 6}
export const DNT104 = {"code": "DNT104", "title": "Droit du numérique", "ects": 4}
export const DRS101 = {"code": "DRS101", "title": "Droit du travail : relations individuelles", "ects": 6}
export const DRS102 = {"code": "DRS102", "title": "Droit du travail : relations collectives", "ects": 6}
export const DRS106 = {"code": "DRS106", "title": "Droit social européen et international", "ects": 6}
export const DSY101 = {"code": "DSY101", "title": "L'organisation & ses modèles : Panorama (1)", "ects": 6}
export const DVE207 = {"code": "DVE207", "title": "Droit et pratique des contrats internationaux", "ects": 6}
export const ELE015 = {"code": "ELE015", "title": "Introduction a l'électronique numérique", "ects": 6}
export const ENG210 = {"code": "ENG210", "title": "Ingénieur de demain", "ects": 6}
export const ENG221 = {"code": "ENG221", "title": "Information et communication pour l'ingénieur - Oral probatoire", "ects": 6}
export const ENG251 = {"code": "ENG251", "title": "Information et communication pour l'ingénieur - Oral probatoire", "ects": 3}
export const ENG261 = {"code": "ENG261", "title": "Information et communication scientifique", "ects": 3}
export const ERG105 = {"code": "ERG105", "title": "Santé, performance et développement au travail", "ects": 6}
export const ESC101 = {"code": "ESC101", "title": "Mercatique I : Les Etudes de marché et les nouveaux enjeux de la Data", "ects": 6}
export const ESD104 = {"code": "ESD104", "title": "Politiques et stratégies économiques dans la mondialisation", "ects": 6}
export const FAB121 = {"code": "FAB121", "title": "Outils et méthodes du Lean", "ects": 6}
export const FAD111 = {"code": "FAD111", "title": "Analyse du travail et ingénierie de la formation professionnelle", "ects": 8}
export const FPG114 = {"code": "FPG114", "title": "Outils RH", "ects": 6}
export const GDN100 = {"code": "GDN100", "title": "Management de projet", "ects": 4}
export const GFN106 = {"code": "GFN106", "title": "Pilotage financier de l'entreprise", "ects": 6}
export const GLG101 = {"code": "GLG101", "title": "Test et Validation du Logiciel", "ects": 6}
export const GLG105 = {"code": "GLG105", "title": "Génie logiciel", "ects": 6}
export const GLG203 = {"code": "GLG203", "title": "Architectures Logicielles Java(1)", "ects": 6}
export const GLG204 = {"code": "GLG204", "title": "Architectures Logicielles Java(2)", "ects": 6}
export const GLG206 = {"code": "GLG206", "title": "Projets informatiques : méthodes et outils (1)", "ects": 6}
export const GLG207 = {"code": "GLG207", "title": "Projets informatiques : méthodes et outils (2)", "ects": 6}
export const GME101 = {"code": "GME101", "title": "Genre et travail", "ects": 6}
export const HSE133 = {"code": "HSE133", "title": "Enjeux des transitions écologiques: comprendre et agir", "ects": 3}
export const HSE134 = {"code": "HSE134", "title": "Intégrer les enjeux de transitions écologiques dans les pratiques professionnelles", "ects": 3}
export const HSE225 = {"code": "HSE225", "title": "Eléments de santé au travail pour les ingénieurs et les managers (ESTIM)", "ects": 3}
export const MSE102 = {"code": "MSE102", "title": "Management et organisation des entreprises", "ects": 6}
export const MSE103 = {"code": "MSE103", "title": "Management et organisation des entreprises - Compléments", "ects": 3}
export const MSE147 = {"code": "MSE147", "title": "Principes généraux et outils du management d'entreprise", "ects": 9}
export const MTR107 = {"code": "MTR107", "title": "Introduction au management qualité", "ects": 3}
export const MUX101 = {"code": "MUX101", "title": "Multimédia et interaction humain-machine", "ects": 6}
export const MUX102 = {"code": "MUX102", "title": "Interaction humain-machine : conception d'interfaces et expérience utilisateur", "ects": 6}
export const MUX103 = {"code": "MUX103", "title": "Design d'interaction pour mobiles", "ects": 6}
export const MUX104 = {"code": "MUX104", "title": "Synthèse d'image et réalité virtuelle", "ects": 6}
export const MUX205 = {"code": "MUX205", "title": "Média numériques avancés : programmation des jeux vidéo", "ects": 6}
export const MUX206 = {"code": "MUX206", "title": "Médias interactifs avancés : game design des jeux vidéo", "ects": 6}
export const MVA003 = {"code": "MVA003", "title": "Outils mathématiques pour l'informatique (Combinatoire, probabilités, ordre, calcul booléen)", "ects": 6}
export const MVA004 = {"code": "MVA004", "title": "Mathématiques pour l'informatique approfondissement (Automates, codes, graphes et matrices)", "ects": 6}
export const MVA010 = {"code": "MVA010", "title": "Bases de l'analyse mathématique", "ects": 4}
export const NFA003 = {"code": "NFA003", "title": "Principes et fonctionnement des systèmes d'exploitation", "ects": 4}
export const NFA004 = {"code": "NFA004", "title": "Architecture des machines", "ects": 4}
export const NFA006 = {"code": "NFA006", "title": "Structures de données", "ects": 4}
export const NFA007 = {"code": "NFA007", "title": "Méthodes pour l'informatisation", "ects": 4}
export const NFA008 = {"code": "NFA008", "title": "Bases de données", "ects": 6}
export const NFA009 = {"code": "NFA009", "title": "Principes des réseaux informatiques", "ects": 6}
export const NFA010 = {"code": "NFA010", "title": "Graphes et optimisation", "ects": 6}
export const NFA011 = {"code": "NFA011", "title": "Développement d'applications avec les bases de données", "ects": 4}
export const NFA013 = {"code": "NFA013", "title": "Méthodes pour l'informatisation - compléments", "ects": 4}
export const NFA018 = {"code": "NFA018", "title": "Gestion de projet informatique", "ects": 4}
export const NFA019 = {"code": "NFA019", "title": "Projet systèmes d'information : mise en pratique avec Java", "ects": 6}
export const NFA021 = {"code": "NFA021", "title": "Développement web (3) : mise en pratique", "ects": 6}
export const NFA022 = {"code": "NFA022", "title": "Principes et programmation système et réseau pour  smart-phones et tablettes tactiles", "ects": 4}
export const NFA024 = {"code": "NFA024", "title": "Projet application mobile : mise en pratique", "ects": 6}
export const NFA025 = {"code": "NFA025", "title": "Mise en oeuvre de la programmation de smart-phones et tablettes tactiles", "ects": 6}
export const NFA031 = {"code": "NFA031", "title": "Programmation avec Java : notions de base", "ects": 6}
export const NFA032 = {"code": "NFA032", "title": "Programmation  Java : programmation objet", "ects": 6}
export const NFA035 = {"code": "NFA035", "title": "Programmation Java : bibliothèques et patterns", "ects": 4}
export const NFA040 = {"code": "NFA040", "title": "Architecture et langages Web", "ects": 4}
export const NFA041 = {"code": "NFA041", "title": "Programmation Javascript", "ects": 6}
export const NFA042 = {"code": "NFA042", "title": "Développement web côté serveur", "ects": 6}
export const NFE101 = {"code": "NFE101", "title": "Ingénierie d'intégration et d'évolution des systèmes d'information", "ects": 6}
export const NFE103 = {"code": "NFE103", "title": "Méthodologies avancées d'informatisation", "ects": 6}
export const NFE106 = {"code": "NFE106", "title": "Ingénierie et optimisation des bases de données", "ects": 6}
export const NFE107 = {"code": "NFE107", "title": "Architecture d'Entreprise et Urbanisation des Systèmes d'Information", "ects": 6}
export const NFE108 = {"code": "NFE108", "title": "Méthodologies des systèmes d'information", "ects": 6}
export const NFE109 = {"code": "NFE109", "title": "Ingénierie des processus et systèmes d'information", "ects": 6}
export const NFE113 = {"code": "NFE113", "title": "Conception et administration de bases de données", "ects": 6}
export const NFE114 = {"code": "NFE114", "title": "Systèmes d'information web", "ects": 6}
export const NFE115 = {"code": "NFE115", "title": "Introduction à la gestion de données à large échelle", "ects": 6}
export const NFE130 = {"code": "NFE130", "title": "Audit des systèmes d'information", "ects": 6}
export const NFE155 = {"code": "NFE155", "title": "ITIL et la gestion des services des systèmes d'information", "ects": 6}
export const NFE204 = {"code": "NFE204", "title": "Bases de données documentaires et distribuées", "ects": 6}
export const NFE205 = {"code": "NFE205", "title": "Données multimédia et spatio-temporelles", "ects": 6}
export const NFE209 = {"code": "NFE209", "title": "Ingénierie des systèmes d'information - Stratégie et gouvernance du SI et des données, audit informatique", "ects": 6}
export const NFE210 = {"code": "NFE210", "title": "Ingénierie des systèmes d'information - Méthodes avancées de pilotage du SI", "ects": 6}
export const NFE211 = {"code": "NFE211", "title": "Business Intelligence (1)  - Data Warehouses", "ects": 6}
export const NFE212 = {"code": "NFE212", "title": "Business Intelligence (2) - Visualisation et Valorisation", "ects": 6}
export const NFP101 = {"code": "NFP101", "title": "Programmation orientée objet en Python, Java et autres", "ects": 6}
export const NFP103 = {"code": "NFP103", "title": "Spécification et vérification des systèmes distribués", "ects": 6}
export const NFP106 = {"code": "NFP106", "title": "Intelligence artificielle", "ects": 6}
export const NFP107 = {"code": "NFP107", "title": "Systèmes de gestion de bases de données", "ects": 6}
export const NFP108 = {"code": "NFP108", "title": "Spécification et Modélisation Informatiques", "ects": 6}
export const NFP119 = {"code": "NFP119", "title": "Programmation Fonctionnelle : des concepts aux applications web", "ects": 6}
export const NFP121 = {"code": "NFP121", "title": "Programmation avancée", "ects": 6}
export const NSY014 = {"code": "NSY014", "title": "Applications réparties", "ects": 6}
export const NSY102 = {"code": "NSY102", "title": "Intergiciels à objets répartis : conception et implantation", "ects": 6}
export const NSY103 = {"code": "NSY103", "title": "Linux : principes et programmation", "ects": 6}
export const NSY104 = {"code": "NSY104", "title": "Architectures des systèmes informatiques", "ects": 6}
export const NSY107 = {"code": "NSY107", "title": "Architectures Cloud, intégration des applications et sécurité.", "ects": 6}
export const NSY115 = {"code": "NSY115", "title": "Conduite d'un projet informatique", "ects": 6}
export const NSY135 = {"code": "NSY135", "title": "Applications orientées données - patrons, frameworks, ORM", "ects": 6}
export const NSY205 = {"code": "NSY205", "title": "Architectures et technologies pour l'intégration des systèmes", "ects": 6}
export const NSY206 = {"code": "NSY206", "title": "Méthodologie d'ingénierie et d'intégration des systèmes", "ects": 6}
export const NSY208 = {"code": "NSY208", "title": "Architecture, Patterns, et Intégration : systèmes embarqués et mobiles en Java et Android (1)", "ects": 6}
export const NSY209 = {"code": "NSY209", "title": "Architecture, Patterns, et Intégration : systèmes embarqués et mobiles en Java et Android (2)", "ects": 6}
export const NTD217 = {"code": "NTD217", "title": "Principes et fondamentaux de la gouvernance des connaissances", "ects": 3}
export const PRS201 = {"code": "PRS201", "title": "Prospective, décision, transformation", "ects": 6}
export const RCP101 = {"code": "RCP101", "title": "Recherche opérationnelle et aide à la décision", "ects": 6}
export const RCP103 = {"code": "RCP103", "title": "Evaluation de performances et sûreté de fonctionnement", "ects": 6}
export const RCP104 = {"code": "RCP104", "title": "Optimisation en informatique", "ects": 6}
export const RCP105 = {"code": "RCP105", "title": "Modélisation, optimisation, complexité et algorithmes", "ects": 6}
export const RCP106 = {"code": "RCP106", "title": "Algorithmique et Programmation", "ects": 6}
export const RCP110 = {"code": "RCP110", "title": "Recherche opérationnelle et programmation linéaire avancée", "ects": 6}
export const RCP207 = {"code": "RCP207", "title": "Modélisation et Analyse de Systèmes Orientés Processus", "ects": 6}
export const RCP208 = {"code": "RCP208", "title": "Apprentissage statistique : modélisation descriptive et introduction aux réseaux de neurones", "ects": 6}
export const RCP209 = {"code": "RCP209", "title": "Apprentissage statistique : modélisation décisionnelle et apprentissage profond", "ects": 6}
export const RCP216 = {"code": "RCP216", "title": "Ingénierie de la fouille et de la visualisation de données massives", "ects": 6}
export const RCP219 = {"code": "RCP219", "title": "Outils mathématiques pour loptimisation numérique et combinatoire", "ects": 6}
export const RCP220 = {"code": "RCP220", "title": "Apprentissage statistique en production", "ects": 6}
export const RSX101 = {"code": "RSX101", "title": "Réseaux et protocoles pour l'Internet", "ects": 6}
export const RSX102 = {"code": "RSX102", "title": "Technologies pour les applications en réseau", "ects": 6}
export const RSX103 = {"code": "RSX103", "title": "Conception et urbanisation de services réseau", "ects": 6}
export const RSX112 = {"code": "RSX112", "title": "Sécurité des réseaux", "ects": 6}
export const RSX116 = {"code": "RSX116", "title": "Réseaux mobiles et sans fil", "ects": 6}
export const RSX217 = {"code": "RSX217", "title": "Nouvelles architectures de réseaux de communication", "ects": 6}
export const RSX218 = {"code": "RSX218", "title": "Projets avancés en réseaux", "ects": 6}
export const RTC201 = {"code": "RTC201", "title": "Socio-histoire de l'innovation techno-scientifique", "ects": 4}
export const SEC101 = {"code": "SEC101", "title": "Cybersécurité : référentiel, objectifs et déploiement", "ects": 6}
export const SEC102 = {"code": "SEC102", "title": "Menaces informatiques et codes malveillants : analyse et lutte", "ects": 6}
export const SEC104 = {"code": "SEC104", "title": "Analyse de risques des données, réseaux et systèmes", "ects": 6}
export const SEC105 = {"code": "SEC105", "title": "Architectures et bonnes pratiques de la sécurité des réseaux, des systèmes, des données et des applications", "ects": 6}
export const SEC106 = {"code": "SEC106", "title": "Analyses de sécurité : vulnérabilités et attaques", "ects": 6}
export const SEC107 = {"code": "SEC107", "title": "Conception d'architecture de sécurité à partir d'un audit de sécurité", "ects": 6}
export const SEC108 = {"code": "SEC108", "title": "Durcissement et mise en uvre de mesures de sécurité avancées pour les données, les réseaux et les systèmes (Hardening)", "ects": 6}
export const SEC201 = {"code": "SEC201", "title": "IAML : IA et du ML pour la cybersécurité", "ects": 6}
export const SEC202 = {"code": "SEC202", "title": "SACE Sécurité d'Architectures Complexes et Émergentes", "ects": 6}
export const SMB101 = {"code": "SMB101", "title": "Systèmes d'exploitation : principes, programmation et virtualisation", "ects": 6}
export const SMB111 = {"code": "SMB111", "title": "Systèmes et applications répartis pour le cloud", "ects": 6}
export const SMB116 = {"code": "SMB116", "title": "Conception et développement pour systèmes mobiles", "ects": 6}
export const SMB214 = {"code": "SMB214", "title": "Infrastructure technologique et nouveaux systèmes (1)", "ects": 6}
export const SMB215 = {"code": "SMB215", "title": "Infrastructure technologique et confiance (2)", "ects": 6}
export const STA001 = {"code": "STA001", "title": "Techniques de la statistique", "ects": 6}
export const STA201 = {"code": "STA201", "title": "Analyse multivariée approfondie", "ects": 9}
export const STA211 = {"code": "STA211", "title": "Entreposage et fouille de données", "ects": 9}
export const TED001 = {"code": "TED001", "title": "Enjeux des transitions écologiques: comprendre et agir", "ects": 3}
export const TET102 = {"code": "TET102", "title": "Management d'équipe et communication en entreprise", "ects": 6}
export const UA2B30 = {"code": "UA2B30", "title": "Test d'anglais", "ects": 0}
export const UAAD91 = {"code": "UAAD91", "title": "Examen d'admission à l'école d'ingénieur", "ects": 0}
export const UAAL0S = {"code": "UAAL0S", "title": "Expérience professionnelle", "ects": 50}
export const UAAL0T = {"code": "UAAL0T", "title": "Expérience professionnelle", "ects": 17}
export const UAEP01 = {"code": "UAEP01", "title": "Expérience professionnelle", "ects": 9}
export const UAEP02 = {"code": "UAEP02", "title": "Expérience professionnelle", "ects": 9}
export const UAEP03 = {"code": "UAEP03", "title": "Expérience professionnelle", "ects": 15}
export const UAEP04 = {"code": "UAEP04", "title": "Expérience professionnelle", "ects": 18}
export const UAM91B = {"code": "UAM91B", "title": "Mémoire ingénieur", "ects": 39}
export const UAMM91 = {"code": "UAMM91", "title": "Mémoire ingénieur", "ects": 42}
export const UATN01 = {"code": "UATN01", "title": "Activités liées à l'international", "ects": 3}
export const UEU001 = {"code": "UEU001", "title": "Union européenne : enjeux et grands débats", "ects": 4}
export const UEU002 = {"code": "UEU002", "title": "Mondialisation et Union européenne", "ects": 4}
export const UTC501 = {"code": "UTC501", "title": "Outils mathématiques pour Informatique", "ects": 3}
export const UTC502 = {"code": "UTC502", "title": "Principes fondamentaux des Systèmes d'exploitation", "ects": 3}
export const UTC503 = {"code": "UTC503", "title": "Paradigmes de programmation", "ects": 3}
export const UTC504 = {"code": "UTC504", "title": "Systèmes d'Information et Bases de Données", "ects": 3}
export const UTC505 = {"code": "UTC505", "title": "Introduction à la cyberstructure de l'internet : réseaux et sécurité", "ects": 3}
